# Generated by Django 5.0 on 2024-05-07 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_createdatdata_user_createdattime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='createdAtData',
        ),
        migrations.AddField(
            model_name='user',
            name='createdAtDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
