# Generated by Django 5.0 on 2024-05-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_createdatdata_user_createdatdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='createdAtDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='createdAtTime',
        ),
    ]
