# Generated by Django 5.0 on 2024-05-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('title', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('createdAtTime', models.TimeField(auto_now_add=True)),
                ('createdAtDate', models.DateField(auto_now_add=True)),
                ('updatedAtTime', models.TimeField(auto_now=True)),
                ('updatedAtDate', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
        ),
    ]
