# Generated by Django 5.0.4 on 2024-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=10)),
                ('content', models.TextField(max_length=1000)),
                ('createdAtTime', models.TimeField(auto_now_add=True)),
                ('createdAtDate', models.DateField(auto_now_add=True)),
                ('updatedAtTime', models.TimeField(auto_now=True)),
                ('updatedAtDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
