# Generated by Django 5.0.4 on 2024-05-13 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('postID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=10)),
                ('content', models.TextField(max_length=1000)),
                ('createdAtTime', models.TimeField(auto_now_add=True)),
                ('createdAtDate', models.DateField(auto_now_add=True)),
                ('updatedAtTime', models.TimeField(auto_now=True)),
                ('updatedAtDate', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
        ),
    ]
